import React, { useState } from 'react';
import { Key, AlertCircle, ArrowRight, ShieldCheck, Loader2 } from 'lucide-react';
import { verifyVaultSessionInCloud } from '../lib/supabase';

export default function SyncPromptScreen({ onPairCode, onUseDemo }) {
  const [inputCode, setInputCode] = useState('');
  const [errorMsg, setErrorMsg] = useState('');
  const [isSyncing, setIsSyncing] = useState(false);

  const handleInputChange = (e) => {
    if (errorMsg) setErrorMsg('');
    let raw = e.target.value.toUpperCase();

    // Remove any non-alphanumeric characters (keep max 8 total)
    let clean = raw.replace(/[^A-Z0-9]/g, '').slice(0, 8);

    const isBackspace = e.nativeEvent && e.nativeEvent.inputType === 'deleteContentBackward';

    if (clean.length > 2) {
      setInputCode(`${clean.slice(0, 2)}-${clean.slice(2)}`);
    } else if (clean.length === 2) {
      if (isBackspace) {
        setInputCode(clean);
      } else {
        setInputCode(`${clean}-`);
      }
    } else {
      setInputCode(clean);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMsg('');
    const raw = inputCode.trim();

    const clean = raw.replace(/[^A-Z0-9]/g, '');

    if (clean.length !== 8) {
      setErrorMsg('Invalid Code length! Vault Code must contain 8 total characters (e.g. SP-623440).');
      return;
    }

    const formattedCode = `${clean.slice(0, 2)}-${clean.slice(2)}`;
    setIsSyncing(true);

    // STRICT CHECK: Verify if Vault Session exists in Supabase (registered by Mobile App)
    const { exists } = await verifyVaultSessionInCloud(formattedCode);

    if (!exists && formattedCode !== 'SP-894201') {
      setIsSyncing(false);
      setErrorMsg(`Vault Code "${formattedCode}" is NOT registered! Please open your Auto Track mobile app, complete onboarding, and register your vault first.`);
      return;
    }

    setIsSyncing(false);
    onPairCode(formattedCode);
  };

  return (
    <div className="min-h-screen bg-[#090d16] flex items-center justify-center p-4 selection:bg-emerald-500 selection:text-white">
      <div className="glass-panel w-full max-w-md rounded-3xl p-8 shadow-2xl border border-slate-800 relative overflow-hidden">
        
        {/* Glowing aura background */}
        <div className="absolute top-0 right-0 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 left-0 w-48 h-48 bg-teal-500/10 rounded-full blur-3xl"></div>

        {/* Brand Header */}
        <div className="text-center mb-8 relative z-10">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-emerald-600 to-teal-400 p-0.5 mx-auto mb-4 shadow-xl shadow-emerald-950/50">
            <div className="w-full h-full bg-slate-950 rounded-[14px] flex items-center justify-center">
              <Key className="w-8 h-8 text-emerald-400" />
            </div>
          </div>
          <h2 className="text-2xl font-bold text-white tracking-tight">Sync Auto Track Vault</h2>
          <p className="text-xs text-slate-400 mt-2 max-w-xs mx-auto">
            Enter the 8-character Vault Sync Code generated by your mobile app to unlock end-to-end encrypted financial data.
          </p>
        </div>

        {/* Sync Input Form */}
        <form onSubmit={handleSubmit} className="space-y-5 relative z-10">
          <div>
            <label className="block text-xs font-bold text-slate-300 uppercase tracking-wider mb-2">
              Vault Sync Code
            </label>
            <div className="relative">
              <input
                type="text"
                value={inputCode}
                onChange={handleInputChange}
                placeholder="SP-623440"
                maxLength={9}
                className="w-full bg-slate-900/90 border border-slate-700/80 focus:border-emerald-500 rounded-2xl py-3.5 px-4 text-center font-mono text-xl font-bold tracking-widest text-emerald-400 placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-emerald-500/20 transition-all uppercase"
              />
              <div className="absolute right-4 top-1/2 -translate-y-1/2 text-xs font-mono text-slate-500">
                {inputCode.replace('-', '').length}/8
              </div>
            </div>
          </div>

          {errorMsg && (
            <div className="p-3 rounded-xl bg-rose-500/10 border border-rose-500/20 text-rose-400 text-xs flex items-center gap-2 animate-fadeIn">
              <AlertCircle className="w-4 h-4 flex-shrink-0" />
              <span>{errorMsg}</span>
            </div>
          )}

          <button
            type="submit"
            disabled={isSyncing}
            className="w-full py-3.5 px-4 rounded-2xl bg-gradient-to-r from-emerald-500 via-emerald-600 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-white font-bold text-sm shadow-xl shadow-emerald-950/60 flex items-center justify-center gap-2 transition-all active:scale-[0.98] disabled:opacity-50"
          >
            {isSyncing ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                <span>Verifying Cloud Vault Code...</span>
              </>
            ) : (
              <>
                <span>Pair & Unlock Dashboard</span>
                <ArrowRight className="w-4 h-4" />
              </>
            )}
          </button>
        </form>

        {/* Demo Mode Button */}
        <div className="mt-6 text-center relative z-10 border-t border-slate-800/80 pt-6">
          <p className="text-xs text-slate-400 mb-3">Don't have the mobile app installed?</p>
          <button
            onClick={onUseDemo}
            className="text-xs font-bold text-emerald-400 hover:text-emerald-300 underline underline-offset-4 transition-colors flex items-center justify-center gap-1.5 mx-auto"
          >
            <ShieldCheck className="w-4 h-4" />
            <span>Launch Live Demo Vault (SP-894201)</span>
          </button>
        </div>

      </div>
    </div>
  );
}
